<h1>Na co se to dívám?</h1>
<p>
To co vidíte je <a rel="external" href="http://www.cs.umd.edu/hcil/treemap/">treemap</a>,
typ vizuálního zobrazení běžně používaného pro data rozdělená do hierarchických kategorií.
</p>

<h2>Co mi toto zobrazení může sdělit?</h2>
<p>
Tato „mapa“ vám může pomoci rozpoznat jak jsour knihy a&nbsp;další dokumenty odpovídající vašemu hledání rozděleny napříč určitými tématy (například podle signatur)
a&nbsp;která témata jsou daným výsledkem pokryta.
</p>
<p>
Poznámka: většina položek v katalogu má pravděpodobně více témat a&nbsp;celkový počet pokrytých témat může být i&nbsp;větší než počet výsledků.
</p>

<h2>Jak s tímto zobrazením zacházet?</h2>
<p>
Kliknutím na širší téma se „mapa“ zaměří pouze na tuto oblast a&nbsp;zobrazí se témata této oblasti.
Na ta je možné dále kliknout pro zobrazení konkrétních položek týkajících se daného tématu.
Tento postup můžete kombinovat použitím upřesnění po levé straně jako jste zvyklí z&nbsp;běžného hledání.
</p>
<p>
Pokud některý popisný text nevidíte celý, stačí najet myší na daný obdélník a&nbsp;text se zobrazí celý.
</p>
